# Generated by Django 5.0.1 on 2024-03-30 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_20', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='customer',
        ),
    ]
