# Generated by Django 5.0.1 on 2024-03-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_20', '0002_rename_user_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='User_id',
            field=models.CharField(max_length=100),
        ),
    ]
