# Generated by Django 5.0.1 on 2024-04-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_20', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='User_id',
            field=models.CharField(max_length=100),
        ),
    ]
