# Generated by Django 5.0.1 on 2024-04-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_20', '0005_alter_payment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='User_id',
            field=models.IntegerField(),
        ),
    ]
