# Generated by Django 5.0.1 on 2024-04-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_20', '0008_payments_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='User_id',
            field=models.CharField(max_length=100),
        ),
    ]
